# Generated by Django 5.1.1 on 2026-10-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reviews",
            "0004_alter_category_options_alter_genre_options_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_review"
            ),
        ),
    ]
