# Generated by Django 5.1.1 on 2026-10-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_alter_category_name_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
        migrations.AlterField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                related_name="titles", to="reviews.genre", verbose_name="Жанр"
            ),
        ),
    ]
